import type { ComponentType, LazyExoticComponent } from 'react';
import { lazy } from 'react';

export type AppCategory =
  | 'crm'
  | 'productividad'
  | 'utilidades'
  | 'multimedia'
  | 'herramientas'
  | 'juegos'
  | 'sistema';

export interface AppDefinition {
  id: string;
  name: string;
  icon: string;
  category: AppCategory;
  component: LazyExoticComponent<ComponentType>;
  defaultWidth: number;
  defaultHeight: number;
  minWidth: number;
  minHeight: number;
  resizable: boolean;
  singleInstance: boolean;
}

// Category display names
export const categoryLabels: Record<AppCategory | 'todas', string> = {
  todas: 'Todas',
  crm: 'CRM',
  productividad: 'Productividad',
  utilidades: 'Utilidades',
  multimedia: 'Multimedia',
  herramientas: 'Herramientas',
  juegos: 'Juegos',
  sistema: 'Sistema',
};

// Category colors for app icons
export const categoryColors: Record<AppCategory, string> = {
  crm: '#d4a853',
  productividad: '#3b82f6',
  utilidades: '#6b7280',
  multimedia: '#8b5cf6',
  herramientas: '#22c55e',
  juegos: '#a855f7',
  sistema: '#64748b',
};

// Helper to create lazy imports
function appLoader(path: string) {
  return lazy(() => import(`@/apps/${path}/index.tsx`));
}

export const appRegistry: AppDefinition[] = [
  // ========== CRM ==========
  {
    id: 'cerebro_crm',
    name: 'Cerebro Promurcia',
    icon: 'Brain',
    category: 'crm',
    component: appLoader('cerebro_crm'),
    defaultWidth: 1200,
    defaultHeight: 750,
    minWidth: 900,
    minHeight: 600,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'crm_dashboard',
    name: 'CRM Panel',
    icon: 'LayoutDashboard',
    category: 'crm',
    component: appLoader('crm_dashboard'),
    defaultWidth: 1200,
    defaultHeight: 750,
    minWidth: 900,
    minHeight: 600,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'crm_leads',
    name: 'CRM Leads',
    icon: 'Users',
    category: 'crm',
    component: appLoader('crm_leads'),
    defaultWidth: 1200,
    defaultHeight: 750,
    minWidth: 900,
    minHeight: 600,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'crm_properties',
    name: 'CRM Propiedades',
    icon: 'Building2',
    category: 'crm',
    component: appLoader('crm_properties'),
    defaultWidth: 1200,
    defaultHeight: 750,
    minWidth: 900,
    minHeight: 600,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'crm_operations',
    name: 'CRM Operaciones',
    icon: 'GitBranch',
    category: 'crm',
    component: appLoader('crm_operations'),
    defaultWidth: 1200,
    defaultHeight: 750,
    minWidth: 900,
    minHeight: 600,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'crm_reports',
    name: 'CRM Informes',
    icon: 'BarChart3',
    category: 'crm',
    component: appLoader('crm_reports'),
    defaultWidth: 1200,
    defaultHeight: 750,
    minWidth: 900,
    minHeight: 600,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'crm_knowledge',
    name: 'CRM Conocimiento',
    icon: 'BookOpen',
    category: 'crm',
    component: appLoader('crm_knowledge'),
    defaultWidth: 1000,
    defaultHeight: 700,
    minWidth: 800,
    minHeight: 500,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'crm_settings',
    name: 'CRM Ajustes',
    icon: 'Cog',
    category: 'crm',
    component: appLoader('crm_settings'),
    defaultWidth: 900,
    defaultHeight: 650,
    minWidth: 700,
    minHeight: 500,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'mortgage_calc',
    name: 'Calculadora Hipotecaria',
    icon: 'Home',
    category: 'crm',
    component: appLoader('mortgage_calc'),
    defaultWidth: 700,
    defaultHeight: 600,
    minWidth: 500,
    minHeight: 400,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'roi_calc',
    name: 'Calculadora ROI',
    icon: 'TrendingUp',
    category: 'crm',
    component: appLoader('roi_calc'),
    defaultWidth: 700,
    defaultHeight: 600,
    minWidth: 500,
    minHeight: 400,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'price_estimator',
    name: 'Estimador Precios',
    icon: 'DollarSign',
    category: 'crm',
    component: appLoader('price_estimator'),
    defaultWidth: 700,
    defaultHeight: 550,
    minWidth: 500,
    minHeight: 400,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'property_compare',
    name: 'Comparador Propiedades',
    icon: 'Columns',
    category: 'crm',
    component: appLoader('property_compare'),
    defaultWidth: 900,
    defaultHeight: 650,
    minWidth: 700,
    minHeight: 500,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'zone_heatmap',
    name: 'Mapa de Calor',
    icon: 'Flame',
    category: 'crm',
    component: appLoader('zone_heatmap'),
    defaultWidth: 900,
    defaultHeight: 700,
    minWidth: 600,
    minHeight: 500,
    resizable: true,
    singleInstance: true,
  },

  // ========== PRODUCTIVIDAD ==========
  {
    id: 'calendar',
    name: 'Calendario',
    icon: 'Calendar',
    category: 'productividad',
    component: appLoader('calendar'),
    defaultWidth: 900,
    defaultHeight: 650,
    minWidth: 500,
    minHeight: 400,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'notes',
    name: 'Notas',
    icon: 'StickyNote',
    category: 'productividad',
    component: appLoader('notes'),
    defaultWidth: 800,
    defaultHeight: 600,
    minWidth: 400,
    minHeight: 300,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'contacts',
    name: 'Contactos',
    icon: 'Contact',
    category: 'productividad',
    component: appLoader('contacts'),
    defaultWidth: 800,
    defaultHeight: 600,
    minWidth: 500,
    minHeight: 400,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'texteditor',
    name: 'Editor de Texto',
    icon: 'FileText',
    category: 'productividad',
    component: appLoader('texteditor'),
    defaultWidth: 900,
    defaultHeight: 650,
    minWidth: 500,
    minHeight: 400,
    resizable: true,
    singleInstance: false,
  },
  {
    id: 'calculator',
    name: 'Calculadora',
    icon: 'Calculator',
    category: 'productividad',
    component: appLoader('calculator'),
    defaultWidth: 360,
    defaultHeight: 520,
    minWidth: 360,
    minHeight: 520,
    resizable: false,
    singleInstance: true,
  },
  {
    id: 'converter',
    name: 'Conversor Unidades',
    icon: 'ArrowRightLeft',
    category: 'productividad',
    component: appLoader('converter'),
    defaultWidth: 600,
    defaultHeight: 500,
    minWidth: 400,
    minHeight: 350,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'clock',
    name: 'Reloj Mundial',
    icon: 'Clock',
    category: 'productividad',
    component: appLoader('clock'),
    defaultWidth: 600,
    defaultHeight: 500,
    minWidth: 400,
    minHeight: 350,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'pdfviewer',
    name: 'Visor de PDF',
    icon: 'FileType',
    category: 'productividad',
    component: appLoader('pdfviewer'),
    defaultWidth: 900,
    defaultHeight: 700,
    minWidth: 500,
    minHeight: 400,
    resizable: true,
    singleInstance: false,
  },
  {
    id: 'photos',
    name: 'Visor de Fotos',
    icon: 'Image',
    category: 'productividad',
    component: appLoader('photos'),
    defaultWidth: 900,
    defaultHeight: 650,
    minWidth: 500,
    minHeight: 400,
    resizable: true,
    singleInstance: true,
  },

  // ========== UTILIDADES ==========
  {
    id: 'terminal',
    name: 'Terminal',
    icon: 'Terminal',
    category: 'utilidades',
    component: appLoader('terminal'),
    defaultWidth: 800,
    defaultHeight: 550,
    minWidth: 400,
    minHeight: 300,
    resizable: true,
    singleInstance: false,
  },
  {
    id: 'filemanager',
    name: 'Gestor de Archivos',
    icon: 'FolderOpen',
    category: 'utilidades',
    component: appLoader('filemanager'),
    defaultWidth: 850,
    defaultHeight: 600,
    minWidth: 500,
    minHeight: 400,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'settings',
    name: 'Configuracion',
    icon: 'Settings',
    category: 'utilidades',
    component: appLoader('settings'),
    defaultWidth: 700,
    defaultHeight: 550,
    minWidth: 500,
    minHeight: 400,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'task_manager_os',
    name: 'Monitor de Sistema',
    icon: 'Activity',
    category: 'utilidades',
    component: appLoader('task_manager_os'),
    defaultWidth: 700,
    defaultHeight: 550,
    minWidth: 500,
    minHeight: 400,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'password_manager',
    name: 'Generador de Passwords',
    icon: 'KeyRound',
    category: 'utilidades',
    component: appLoader('password_manager'),
    defaultWidth: 500,
    defaultHeight: 400,
    minWidth: 400,
    minHeight: 350,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'paint',
    name: 'Bloc de Dibujo',
    icon: 'Palette',
    category: 'utilidades',
    component: appLoader('paint'),
    defaultWidth: 800,
    defaultHeight: 600,
    minWidth: 500,
    minHeight: 400,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'weather',
    name: 'Clima',
    icon: 'CloudSun',
    category: 'utilidades',
    component: appLoader('weather'),
    defaultWidth: 500,
    defaultHeight: 600,
    minWidth: 400,
    minHeight: 500,
    resizable: true,
    singleInstance: true,
  },

  // ========== MULTIMEDIA ==========
  {
    id: 'music',
    name: 'Reproductor de Musica',
    icon: 'Music',
    category: 'multimedia',
    component: appLoader('music'),
    defaultWidth: 900,
    defaultHeight: 600,
    minWidth: 500,
    minHeight: 400,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'video_player',
    name: 'Reproductor de Video',
    icon: 'Video',
    category: 'multimedia',
    component: appLoader('video_player'),
    defaultWidth: 900,
    defaultHeight: 600,
    minWidth: 500,
    minHeight: 350,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'drawing_pad',
    name: 'Editor de Audio',
    icon: 'AudioLines',
    category: 'multimedia',
    component: appLoader('drawing_pad'),
    defaultWidth: 900,
    defaultHeight: 600,
    minWidth: 500,
    minHeight: 400,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'voice_recorder',
    name: 'Grabador de Pantalla',
    icon: 'MonitorPlay',
    category: 'multimedia',
    component: appLoader('voice_recorder'),
    defaultWidth: 600,
    defaultHeight: 450,
    minWidth: 400,
    minHeight: 300,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'rss_reader',
    name: 'Reproductor de Radio',
    icon: 'Radio',
    category: 'multimedia',
    component: appLoader('rss_reader'),
    defaultWidth: 700,
    defaultHeight: 550,
    minWidth: 500,
    minHeight: 400,
    resizable: true,
    singleInstance: true,
  },

  // ========== HERRAMIENTAS ==========
  {
    id: 'dictionary',
    name: 'Diccionario',
    icon: 'BookMarked',
    category: 'herramientas',
    component: appLoader('dictionary'),
    defaultWidth: 600,
    defaultHeight: 500,
    minWidth: 400,
    minHeight: 350,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'translator',
    name: 'Traductor',
    icon: 'Languages',
    category: 'herramientas',
    component: appLoader('translator'),
    defaultWidth: 600,
    defaultHeight: 500,
    minWidth: 400,
    minHeight: 350,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'bmi',
    name: 'Calculadora de IMC',
    icon: 'HeartPulse',
    category: 'herramientas',
    component: appLoader('bmi'),
    defaultWidth: 500,
    defaultHeight: 550,
    minWidth: 400,
    minHeight: 450,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'base_converter',
    name: 'Conversor de Bases',
    icon: 'Binary',
    category: 'herramientas',
    component: appLoader('base_converter'),
    defaultWidth: 550,
    defaultHeight: 450,
    minWidth: 400,
    minHeight: 350,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'tip_calc',
    name: 'Calculadora de Propinas',
    icon: 'Banknote',
    category: 'herramientas',
    component: appLoader('tip_calc'),
    defaultWidth: 450,
    defaultHeight: 500,
    minWidth: 350,
    minHeight: 400,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'qr_code',
    name: 'Lector de Codigos QR',
    icon: 'QrCode',
    category: 'herramientas',
    component: appLoader('qr_code'),
    defaultWidth: 500,
    defaultHeight: 500,
    minWidth: 400,
    minHeight: 400,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'discount_calc',
    name: 'Calculadora de Descuentos',
    icon: 'Tag',
    category: 'herramientas',
    component: appLoader('discount_calc'),
    defaultWidth: 450,
    defaultHeight: 450,
    minWidth: 350,
    minHeight: 350,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'quick_notes_widget',
    name: 'Notas Rapidas',
    icon: 'Pin',
    category: 'herramientas',
    component: appLoader('quick_notes_widget'),
    defaultWidth: 350,
    defaultHeight: 400,
    minWidth: 250,
    minHeight: 300,
    resizable: true,
    singleInstance: false,
  },
  {
    id: 'pomodoro',
    name: 'Pomodoro',
    icon: 'Timer',
    category: 'herramientas',
    component: appLoader('pomodoro'),
    defaultWidth: 400,
    defaultHeight: 450,
    minWidth: 300,
    minHeight: 350,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'browser',
    name: 'Navegador',
    icon: 'Globe',
    category: 'herramientas',
    component: appLoader('browser'),
    defaultWidth: 1000,
    defaultHeight: 700,
    minWidth: 600,
    minHeight: 400,
    resizable: true,
    singleInstance: false,
  },
  {
    id: 'email_client',
    name: 'Email',
    icon: 'Mail',
    category: 'herramientas',
    component: appLoader('email_client'),
    defaultWidth: 900,
    defaultHeight: 650,
    minWidth: 600,
    minHeight: 450,
    resizable: true,
    singleInstance: true,
  },

  // ========== JUEGOS ==========
  {
    id: 'snake',
    name: 'Snake',
    icon: 'Gamepad2',
    category: 'juegos',
    component: appLoader('snake'),
    defaultWidth: 700,
    defaultHeight: 600,
    minWidth: 400,
    minHeight: 400,
    resizable: false,
    singleInstance: true,
  },
  {
    id: 'tetris',
    name: 'Tetris',
    icon: 'LayoutGrid',
    category: 'juegos',
    component: appLoader('tetris'),
    defaultWidth: 500,
    defaultHeight: 700,
    minWidth: 400,
    minHeight: 500,
    resizable: false,
    singleInstance: true,
  },
  {
    id: 'pong',
    name: 'Pong',
    icon: 'Circle',
    category: 'juegos',
    component: appLoader('pong'),
    defaultWidth: 700,
    defaultHeight: 500,
    minWidth: 500,
    minHeight: 400,
    resizable: false,
    singleInstance: true,
  },
  {
    id: 'sudoku',
    name: 'Sudoku',
    icon: 'Grid3x3',
    category: 'juegos',
    component: appLoader('sudoku'),
    defaultWidth: 550,
    defaultHeight: 600,
    minWidth: 400,
    minHeight: 450,
    resizable: false,
    singleInstance: true,
  },
  {
    id: 'minesweeper',
    name: 'Buscaminas',
    icon: 'Bomb',
    category: 'juegos',
    component: appLoader('minesweeper'),
    defaultWidth: 500,
    defaultHeight: 580,
    minWidth: 300,
    minHeight: 350,
    resizable: false,
    singleInstance: true,
  },
  {
    id: 'game_2048',
    name: '2048',
    icon: 'ArrowUp',
    category: 'juegos',
    component: appLoader('game_2048'),
    defaultWidth: 450,
    defaultHeight: 600,
    minWidth: 350,
    minHeight: 450,
    resizable: false,
    singleInstance: true,
  },
  {
    id: 'chess',
    name: 'Ajedrez',
    icon: 'Crown',
    category: 'juegos',
    component: appLoader('chess'),
    defaultWidth: 650,
    defaultHeight: 700,
    minWidth: 450,
    minHeight: 450,
    resizable: false,
    singleInstance: true,
  },
  {
    id: 'tic_tac_toe',
    name: 'Tres en Raya',
    icon: 'Hash',
    category: 'juegos',
    component: appLoader('tic_tac_toe'),
    defaultWidth: 450,
    defaultHeight: 500,
    minWidth: 350,
    minHeight: 350,
    resizable: false,
    singleInstance: true,
  },
  {
    id: 'memory',
    name: 'Memoria',
    icon: 'Brain',
    category: 'juegos',
    component: appLoader('memory'),
    defaultWidth: 600,
    defaultHeight: 600,
    minWidth: 400,
    minHeight: 400,
    resizable: false,
    singleInstance: true,
  },
  {
    id: 'flappy_bird',
    name: 'Flappy Bird',
    icon: 'Bird',
    category: 'juegos',
    component: appLoader('flappy_bird'),
    defaultWidth: 450,
    defaultHeight: 650,
    minWidth: 350,
    minHeight: 500,
    resizable: false,
    singleInstance: true,
  },
  {
    id: 'api_config',
    name: 'Configuracion APIs',
    icon: 'Key',
    category: 'sistema',
    component: appLoader('api_config'),
    defaultWidth: 700,
    defaultHeight: 600,
    minWidth: 500,
    minHeight: 400,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'document_import',
    name: 'Importar Documentos',
    icon: 'FileUp',
    category: 'herramientas',
    component: appLoader('document_import'),
    defaultWidth: 800,
    defaultHeight: 650,
    minWidth: 600,
    minHeight: 450,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'transcriptions',
    name: 'Transcripciones',
    icon: 'AudioLines',
    category: 'herramientas',
    component: appLoader('transcriptions'),
    defaultWidth: 800,
    defaultHeight: 650,
    minWidth: 600,
    minHeight: 450,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'deep_drive_analysis',
    name: 'Análisis Profundo IA',
    icon: 'BrainCircuit',
    category: 'crm',
    component: appLoader('deep_drive_analysis'),
    defaultWidth: 1100,
    defaultHeight: 750,
    minWidth: 800,
    minHeight: 550,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'drive_sync',
    name: 'Drive Sync IA',
    icon: 'Cloud',
    category: 'crm',
    component: appLoader('drive_sync'),
    defaultWidth: 1100,
    defaultHeight: 750,
    minWidth: 800,
    minHeight: 550,
    resizable: true,
    singleInstance: true,
  },
];

// Helper functions
export function getAppById(id: string): AppDefinition | undefined {
  return appRegistry.find((app) => app.id === id);
}

export function getAppsByCategory(category: AppCategory | 'todas'): AppDefinition[] {
  if (category === 'todas') return appRegistry;
  return appRegistry.filter((app) => app.category === category);
}

export function searchApps(query: string): AppDefinition[] {
  const q = query.toLowerCase().trim();
  if (!q) return appRegistry;
  return appRegistry.filter(
    (app) =>
      app.name.toLowerCase().includes(q) ||
      app.category.toLowerCase().includes(q)
  );
}

// Icon mapping for dynamic lucide icon rendering
export const iconMapping: Record<string, string> = {
  Brain: 'Brain', BrainCircuit: 'BrainCircuit', LayoutDashboard: 'LayoutDashboard', Users: 'Users',
  Building2: 'Building2', GitBranch: 'GitBranch', BarChart3: 'BarChart3',
  BookOpen: 'BookOpen', Cog: 'Cog', Home: 'Home', TrendingUp: 'TrendingUp',
  DollarSign: 'DollarSign', Columns: 'Columns', Flame: 'Flame',
  Calendar: 'Calendar', StickyNote: 'StickyNote', Contact: 'Contact',
  FileText: 'FileText', Calculator: 'Calculator', ArrowRightLeft: 'ArrowRightLeft',
  Clock: 'Clock', FileType: 'FileType', Image: 'Image',
  Terminal: 'Terminal', FolderOpen: 'FolderOpen', Settings: 'Settings',
  Activity: 'Activity', KeyRound: 'KeyRound', Key: 'Key', Palette: 'Palette',
  Cloud: 'Cloud', CloudSun: 'CloudSun', Music: 'Music', Video: 'Video',
  AudioLines: 'AudioLines', MonitorPlay: 'MonitorPlay', Radio: 'Radio',
  BookMarked: 'BookMarked', Languages: 'Languages', HeartPulse: 'HeartPulse',
  Binary: 'Binary', Banknote: 'Banknote', QrCode: 'QrCode',
  Tag: 'Tag', Pin: 'Pin', Timer: 'Timer', Globe: 'Globe',
  Mail: 'Mail', Gamepad2: 'Gamepad2', LayoutGrid: 'LayoutGrid',
  Circle: 'Circle', Grid3x3: 'Grid3x3', Bomb: 'Bomb',
  ArrowUp: 'ArrowUp', Crown: 'Crown', Hash: 'Hash', Bird: 'Bird',
  FileUp: 'FileUp',
};
