import type { ComponentType, LazyExoticComponent } from 'react';
import { lazy } from 'react';

export type AppCategory =
  | 'crm'
  | 'productividad'
  | 'utilidades'
  | 'herramientas'
  | 'sistema';

export interface AppDefinition {
  id: string;
  name: string;
  icon: string;
  category: AppCategory;
  component: LazyExoticComponent<ComponentType>;
  defaultWidth: number;
  defaultHeight: number;
  minWidth: number;
  minHeight: number;
  resizable: boolean;
  singleInstance: boolean;
}

// Category display names
export const categoryLabels: Record<AppCategory | 'todas', string> = {
  todas: 'Todas',
  crm: 'CRM',
  productividad: 'Productividad',
  utilidades: 'Utilidades',
  herramientas: 'Herramientas',
  sistema: 'Sistema',
};

// Category colors for app icons
export const categoryColors: Record<AppCategory, string> = {
  crm: '#d4a853',
  productividad: '#3b82f6',
  utilidades: '#6b7280',
  herramientas: '#22c55e',
  sistema: '#64748b',
};

// Helper to create lazy imports
function appLoader(path: string) {
  return lazy(() => import(`@/apps/${path}/index.tsx`));
}

export const appRegistry: AppDefinition[] = [
  // ========== CRM ==========
  {
    id: 'cerebro_crm',
    name: 'Cerebro Promurcia',
    icon: 'Brain',
    category: 'crm',
    component: appLoader('cerebro_crm'),
    defaultWidth: 1200,
    defaultHeight: 750,
    minWidth: 900,
    minHeight: 600,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'crm_dashboard',
    name: 'CRM Panel',
    icon: 'LayoutDashboard',
    category: 'crm',
    component: appLoader('crm_dashboard'),
    defaultWidth: 1200,
    defaultHeight: 750,
    minWidth: 900,
    minHeight: 600,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'crm_leads',
    name: 'CRM Leads',
    icon: 'Users',
    category: 'crm',
    component: appLoader('crm_leads'),
    defaultWidth: 1200,
    defaultHeight: 750,
    minWidth: 900,
    minHeight: 600,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'crm_properties',
    name: 'CRM Propiedades',
    icon: 'Building2',
    category: 'crm',
    component: appLoader('crm_properties'),
    defaultWidth: 1200,
    defaultHeight: 750,
    minWidth: 900,
    minHeight: 600,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'crm_operations',
    name: 'CRM Operaciones',
    icon: 'GitBranch',
    category: 'crm',
    component: appLoader('crm_operations'),
    defaultWidth: 1200,
    defaultHeight: 750,
    minWidth: 900,
    minHeight: 600,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'crm_reports',
    name: 'CRM Informes',
    icon: 'BarChart3',
    category: 'crm',
    component: appLoader('crm_reports'),
    defaultWidth: 1200,
    defaultHeight: 750,
    minWidth: 900,
    minHeight: 600,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'crm_knowledge',
    name: 'CRM Conocimiento',
    icon: 'BookOpen',
    category: 'crm',
    component: appLoader('crm_knowledge'),
    defaultWidth: 1000,
    defaultHeight: 700,
    minWidth: 800,
    minHeight: 500,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'crm_settings',
    name: 'CRM Ajustes',
    icon: 'Cog',
    category: 'crm',
    component: appLoader('crm_settings'),
    defaultWidth: 900,
    defaultHeight: 650,
    minWidth: 700,
    minHeight: 500,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'mortgage_calc',
    name: 'Calculadora Hipotecaria',
    icon: 'Home',
    category: 'crm',
    component: appLoader('mortgage_calc'),
    defaultWidth: 700,
    defaultHeight: 600,
    minWidth: 500,
    minHeight: 400,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'roi_calc',
    name: 'Calculadora ROI',
    icon: 'TrendingUp',
    category: 'crm',
    component: appLoader('roi_calc'),
    defaultWidth: 700,
    defaultHeight: 600,
    minWidth: 500,
    minHeight: 400,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'price_estimator',
    name: 'Estimador Precios',
    icon: 'DollarSign',
    category: 'crm',
    component: appLoader('price_estimator'),
    defaultWidth: 700,
    defaultHeight: 550,
    minWidth: 500,
    minHeight: 400,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'property_compare',
    name: 'Comparador Propiedades',
    icon: 'Columns',
    category: 'crm',
    component: appLoader('property_compare'),
    defaultWidth: 900,
    defaultHeight: 650,
    minWidth: 700,
    minHeight: 500,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'zone_heatmap',
    name: 'Mapa de Calor',
    icon: 'Flame',
    category: 'crm',
    component: appLoader('zone_heatmap'),
    defaultWidth: 900,
    defaultHeight: 700,
    minWidth: 600,
    minHeight: 500,
    resizable: true,
    singleInstance: true,
  },

  // ========== PRODUCTIVIDAD ==========
  {
    id: 'calendar',
    name: 'Calendario',
    icon: 'Calendar',
    category: 'productividad',
    component: appLoader('calendar'),
    defaultWidth: 900,
    defaultHeight: 650,
    minWidth: 500,
    minHeight: 400,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'notes',
    name: 'Notas',
    icon: 'StickyNote',
    category: 'productividad',
    component: appLoader('notes'),
    defaultWidth: 800,
    defaultHeight: 600,
    minWidth: 400,
    minHeight: 300,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'contacts',
    name: 'Contactos',
    icon: 'Contact',
    category: 'productividad',
    component: appLoader('contacts'),
    defaultWidth: 800,
    defaultHeight: 600,
    minWidth: 500,
    minHeight: 400,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'texteditor',
    name: 'Editor de Texto',
    icon: 'FileText',
    category: 'productividad',
    component: appLoader('texteditor'),
    defaultWidth: 900,
    defaultHeight: 650,
    minWidth: 500,
    minHeight: 400,
    resizable: true,
    singleInstance: false,
  },
  {
    id: 'calculator',
    name: 'Calculadora',
    icon: 'Calculator',
    category: 'productividad',
    component: appLoader('calculator'),
    defaultWidth: 360,
    defaultHeight: 520,
    minWidth: 360,
    minHeight: 520,
    resizable: false,
    singleInstance: true,
  },
  {
    id: 'converter',
    name: 'Conversor Unidades',
    icon: 'ArrowRightLeft',
    category: 'productividad',
    component: appLoader('converter'),
    defaultWidth: 600,
    defaultHeight: 500,
    minWidth: 400,
    minHeight: 350,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'clock',
    name: 'Reloj Mundial',
    icon: 'Clock',
    category: 'productividad',
    component: appLoader('clock'),
    defaultWidth: 600,
    defaultHeight: 500,
    minWidth: 400,
    minHeight: 350,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'pdfviewer',
    name: 'Visor de PDF',
    icon: 'FileType',
    category: 'productividad',
    component: appLoader('pdfviewer'),
    defaultWidth: 900,
    defaultHeight: 700,
    minWidth: 500,
    minHeight: 400,
    resizable: true,
    singleInstance: false,
  },
  
  // ========== UTILIDADES ==========
  {
    id: 'terminal',
    name: 'Terminal',
    icon: 'Terminal',
    category: 'utilidades',
    component: appLoader('terminal'),
    defaultWidth: 800,
    defaultHeight: 550,
    minWidth: 400,
    minHeight: 300,
    resizable: true,
    singleInstance: false,
  },
  {
    id: 'filemanager',
    name: 'Gestor de Archivos',
    icon: 'FolderOpen',
    category: 'utilidades',
    component: appLoader('filemanager'),
    defaultWidth: 850,
    defaultHeight: 600,
    minWidth: 500,
    minHeight: 400,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'settings',
    name: 'Configuracion',
    icon: 'Settings',
    category: 'utilidades',
    component: appLoader('settings'),
    defaultWidth: 700,
    defaultHeight: 550,
    minWidth: 500,
    minHeight: 400,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'task_manager_os',
    name: 'Monitor de Sistema',
    icon: 'Activity',
    category: 'utilidades',
    component: appLoader('task_manager_os'),
    defaultWidth: 700,
    defaultHeight: 550,
    minWidth: 500,
    minHeight: 400,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'password_manager',
    name: 'Generador de Passwords',
    icon: 'KeyRound',
    category: 'utilidades',
    component: appLoader('password_manager'),
    defaultWidth: 500,
    defaultHeight: 400,
    minWidth: 400,
    minHeight: 350,
    resizable: true,
    singleInstance: true,
  },
    
  // ========== MULTIMEDIA ==========
          
  // ========== HERRAMIENTAS ==========
        {
    id: 'base_converter',
    name: 'Conversor de Bases',
    icon: 'Binary',
    category: 'herramientas',
    component: appLoader('base_converter'),
    defaultWidth: 550,
    defaultHeight: 450,
    minWidth: 400,
    minHeight: 350,
    resizable: true,
    singleInstance: true,
  },
        {
    id: 'quick_notes_widget',
    name: 'Notas Rapidas',
    icon: 'Pin',
    category: 'herramientas',
    component: appLoader('quick_notes_widget'),
    defaultWidth: 350,
    defaultHeight: 400,
    minWidth: 250,
    minHeight: 300,
    resizable: true,
    singleInstance: false,
  },
      {
    id: 'email_client',
    name: 'Email',
    icon: 'Mail',
    category: 'herramientas',
    component: appLoader('email_client'),
    defaultWidth: 900,
    defaultHeight: 650,
    minWidth: 600,
    minHeight: 450,
    resizable: true,
    singleInstance: true,
  },

  // ========== JUEGOS ==========
                      {
    id: 'api_config',
    name: 'Configuracion APIs',
    icon: 'Key',
    category: 'sistema',
    component: appLoader('api_config'),
    defaultWidth: 700,
    defaultHeight: 600,
    minWidth: 500,
    minHeight: 400,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'phone_lookup',
    name: 'Buscar por Teléfono',
    icon: 'Phone',
    category: 'crm',
    component: appLoader('phone_lookup'),
    defaultWidth: 900,
    defaultHeight: 700,
    minWidth: 600,
    minHeight: 500,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'document_import',
    name: 'Importar Documentos',
    icon: 'FileUp',
    category: 'herramientas',
    component: appLoader('document_import'),
    defaultWidth: 800,
    defaultHeight: 650,
    minWidth: 600,
    minHeight: 450,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'transcriptions',
    name: 'Transcripciones',
    icon: 'AudioLines',
    category: 'herramientas',
    component: appLoader('transcriptions'),
    defaultWidth: 800,
    defaultHeight: 650,
    minWidth: 600,
    minHeight: 450,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'deep_drive_analysis',
    name: 'Análisis Profundo IA',
    icon: 'BrainCircuit',
    category: 'crm',
    component: appLoader('deep_drive_analysis'),
    defaultWidth: 1100,
    defaultHeight: 750,
    minWidth: 800,
    minHeight: 550,
    resizable: true,
    singleInstance: true,
  },
  {
    id: 'drive_sync',
    name: 'Drive Sync IA',
    icon: 'Cloud',
    category: 'crm',
    component: appLoader('drive_sync'),
    defaultWidth: 1100,
    defaultHeight: 750,
    minWidth: 800,
    minHeight: 550,
    resizable: true,
    singleInstance: true,
  },
];

// Helper functions
export function getAppById(id: string): AppDefinition | undefined {
  return appRegistry.find((app) => app.id === id);
}

export function getAppsByCategory(category: AppCategory | 'todas'): AppDefinition[] {
  if (category === 'todas') return appRegistry;
  return appRegistry.filter((app) => app.category === category);
}

export function searchApps(query: string): AppDefinition[] {
  const q = query.toLowerCase().trim();
  if (!q) return appRegistry;
  return appRegistry.filter(
    (app) =>
      app.name.toLowerCase().includes(q) ||
      app.category.toLowerCase().includes(q)
  );
}

// Icon mapping for dynamic lucide icon rendering
export const iconMapping: Record<string, string> = {
  Activity: 'Activity',
  ArrowRightLeft: 'ArrowRightLeft',
  AudioLines: 'AudioLines',
  BarChart3: 'BarChart3',
  Binary: 'Binary',
  BookOpen: 'BookOpen',
  Brain: 'Brain',
  BrainCircuit: 'BrainCircuit',
  Building2: 'Building2',
  Calculator: 'Calculator',
  Calendar: 'Calendar',
  Clock: 'Clock',
  Cloud: 'Cloud',
  Cog: 'Cog',
  Columns: 'Columns',
  Contact: 'Contact',
  DollarSign: 'DollarSign',
  FileText: 'FileText',
  FileType: 'FileType',
  FileUp: 'FileUp',
  Flame: 'Flame',
  FolderOpen: 'FolderOpen',
  GitBranch: 'GitBranch',
  Home: 'Home',
  Key: 'Key',
  KeyRound: 'KeyRound',
  LayoutDashboard: 'LayoutDashboard',
  Mail: 'Mail',
  Phone: 'Phone',
  Pin: 'Pin',
  Settings: 'Settings',
  StickyNote: 'StickyNote',
  Terminal: 'Terminal',
  TrendingUp: 'TrendingUp',
  Users: 'Users'
};
